---
namespace: trippsc2
name: gitea
version: 1.0.1
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains modules and roles for installing, configuring, and maintaining Gitea.

license_file: 'LICENSE'

tags:
  - infrastructure
  - linux
  - tools

dependencies:
  ansible.posix: ">=1.0.0"
  community.general: ">=1.0.0"

repository: https://github.com/trippsc2/ansible-collection-gitea.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
