---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky9_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: gitea_server_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        gitea_server_start_ssh_server: true
verifier:
  name: ansible
