---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Create user
  ansible.builtin.import_tasks: user.yml

- name: Create directories
  ansible.builtin.import_tasks: directories.yml

- name: Install Gitea
  ansible.builtin.import_tasks: install.yml

- name: Configure firewalld
  when:
    - gitea_configure_firewall
    - _gitea_firewall_type == 'firewalld'
  ansible.builtin.include_tasks: firewalld.yml

- name: Configure ufw
  when:
    - gitea_configure_firewall
    - _gitea_firewall_type == 'ufw'
  ansible.builtin.include_tasks: ufw.yml
