---
- name: Create Gitea group
  become: true
  ansible.builtin.group:
    name: "{{ gitea_group }}"
    system: true
    state: present

- name: Create Gitea user
  become: true
  ansible.builtin.user:
    name: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    home: "{{ gitea_user_home }}"
    comment: Gitea
    shell: /usr/sbin/nologin
    create_home: true
    system: true
    state: present
    password: '!'
    password_lock: true
