---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/server/.aar_doc.yml
      - roles/server/README.md
      - roles/server/meta/argument_specs.yml
      - roles/server/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.gitea'
jobs:
  docs_server:
    name: Generate server role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.gitea'
      role_name: 'server'
