---
name: Molecule - server role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/server/**
      - '!roles/server/.aar_doc.yml'
      - '!roles/server/README.md'
      - '!roles/server/meta/argument_specs.yml'
      - '!roles/server/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/server/**
      - '!roles/server/.aar_doc.yml'
      - '!roles/server/README.md'
      - '!roles/server/meta/argument_specs.yml'
      - '!roles/server/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.gitea'
jobs:
  molecule_default:
    name: Run Molecule tests - No reverse proxy
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12_base
          - rocky9_cis
          - rocky8_cis
          - ubuntu2404_base
          - ubuntu2204_base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.gitea'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/server
          molecule test
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
  molecule_reverse_proxy:
    name: Run Molecule tests - Nginx reverse proxy
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - debian12_base
          - rocky9_cis
          - rocky8_cis
          - ubuntu2404_base
          - ubuntu2204_base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.gitea'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/server
          molecule test -s reverse_proxy
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
